language: haskell
ghc:
  - 7.6
  - 7.8

before_install:
  - cabal update
  - cabal install cartel
  - cabal install quickpull
  - cd library
  - sh generate
  - cd ../tests
  - sh generate
  - cd ..

install:
  - cd library
  - cabal install --only-dependencies

script:
  - ghc-pkg list
  - cabal sdist --output-directory=tarball
  - cd tarball
  - cabal install
  - cd ../../tests
  - cabal configure
  - cabal build
  - dist/build/prednote-test/prednote-test
  - dist/build/prednote-visual-test/prednote-visual-test
