language: haskell
ghc:
  - 7.6
  - 7.8

before_install:
  - cabal update
  - cabal install 'cartel < 0.12' quickpull packdeps
  - sh generate
  - packdeps prednote.cabal

install:
  - cabal install --only-dependencies --enable-tests

script:
  - ghc-pkg list
  - cabal sdist --output-directory=tarball
  - cd tarball
  - pwd
  - cabal configure --enable-tests -fvisual-tests
  - cabal build
  - dist/build/prednote-tests/prednote-tests
  - dist/build/prednote-visual-tests/prednote-visual-tests
  - cabal install
